version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql.railway.internal
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: HXCfknROJI1ShLeVuXxEDyfWfwDpckTH
      WORDPRESS_DB_NAME: railway
    restart: always
